# Generated by Django 5.0.1 on 2024-02-06 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='configuration',
            new_name='configurations',
        ),
    ]
